embedding_size: 64
n_ui_layers: 2
n_layers: [1]

learning_rate_scheduler: [0.96, 50]
lambda_coeff: 0.9
reg_weight: 1e-4

knn_k: [10]

learning_rate: [0.005,0.003,0.001,0.0007,0.0005,0.0003,0.0001]
cl_loss: [0.0001,0.001,0.005,0.01,0.1]
# learning_rate: [0.0005]
# cl_loss: [0.01]

sim_weight: [0.1,0.2, 0.3,0.4, 0.5]
ui_cosine_loss_weight: 0.1
# sim_weight: [0.0001,0.001,0.01,0.1,1.0]

hyper_parameters: ["cl_loss","learning_rate","n_layers","knn_k","sim_weight"]